use crate::method::Method;
use crate::type_info::{Field, Number, TypeInfo, Variant};
use std::{collections::HashSet, fmt::Write};
use std::{io, path::Path};
use typescript_type_def::TypeDef;

impl TypeInfo {
    fn qt_type(&self) -> String {
        match self {
            TypeInfo::String => "QString".to_owned(),
            TypeInfo::Bool => "bool".to_owned(),
            TypeInfo::Number(n) => match n {
                Number::I8 => "int8_t",
                Number::I16 => "int16_t",
                Number::I32 => "int32_t",
                Number::I64 => "int64_t",
                Number::U8 => "uint8_t",
                Number::U16 => "uint16_t",
                Number::U32 => "uint32_t",
                Number::U64 => "uint64_t",
                Number::F32 => "float",
                Number::F64 => "double",
            }
            .to_owned(),
            TypeInfo::Optional(o) => {
                format!("std::optional<{}>", o.qt_type())
            }
            TypeInfo::Array(a) => {
                format!("QList<{}>", a.qt_type())
            }
            TypeInfo::Map(v) => {
                format!("QMap<QString, {}>", v.qt_type())
            }
            TypeInfo::Void => "void".to_owned(),
            TypeInfo::Struct { name, .. }
            | TypeInfo::TaggedEnum { name, .. }
            | TypeInfo::StringEnum { name, .. } => name.clone(),
            TypeInfo::Tuple { name, elements } => name.clone().unwrap_or_else(|| {
                format!(
                    "std::tuple<{}>",
                    join_with_comma(elements.iter().map(Self::qt_type))
                )
            }),
        }
    }
}

pub fn export_types_to_file<T: TypeDef>(path: &Path, root_namespace: &str) -> io::Result<()> {
    let mut output = format!(
        r#"// AUTO-GENERATED by yerpc-derive

#pragma once

#include <optional>
#include <cstdint>

#include <QString>
#include <QJsonValue>
#include <QJsonObject>
#include <QJsonArray>

namespace {root_namespace} {{

namespace Hidden {{
    template<class... Ts> struct overloaded : Ts... {{ using Ts::operator()...; }};
    template<class... Ts> overloaded(Ts...) -> overloaded<Ts...>;
}}

"#
    );
    QtJsonGenerator::new().generate(&mut output, &TypeInfo::from(&T::INFO));
    output.push_str("\n}\n");
    std::fs::write(path, output)
}

#[derive(Default)]
pub struct QtJsonGenerator {
    seen: HashSet<String>,
}

impl QtJsonGenerator {
    pub fn new() -> Self {
        Self::default()
    }

    fn generate(&mut self, output: &mut String, ty: &TypeInfo) {
        if !self.seen.insert(ty.qt_type()) {
            return;
        };
        match ty {
            TypeInfo::Struct { name, fields } => {
                self.generate_cpp_struct(output, name, fields);
            }
            TypeInfo::TaggedEnum { name, variants } => {
                self.generate_tagged_union(output, name, variants)
            }
            TypeInfo::StringEnum { name, variants } => {
                self.generate_unit_enum(output, name, variants);
            }
            TypeInfo::Tuple { name, elements } => self.generate_tuple(output, name, elements),
            TypeInfo::Array(v) => self.generate_array(output, v),
            TypeInfo::Optional(inner) => self.generate_optional(output, inner),
            TypeInfo::Map(v) => self.generate_map(output, v),
            TypeInfo::Bool => generate_bool(output),
            TypeInfo::Number(_) => generate_number(output, &ty.qt_type()),
            TypeInfo::String => generate_string(output),
            TypeInfo::Void => (),
        }
    }

    fn generate_tuple(
        &mut self,
        output: &mut String,
        name: &Option<String>,
        elements: &Vec<TypeInfo>,
    ) {
        for e in elements {
            self.generate(output, e);
        }
        let cpp_tuple = format!(
            "std::tuple<{}>",
            join_with_comma(elements.iter().map(|e| e.qt_type()))
        );
        if let Some(name) = name {
            writeln!(output, "using {name} = {cpp_tuple};",).unwrap();
        }
        let name = name.as_ref().unwrap_or(&cpp_tuple);
        writeln!(output, "inline QJsonValue toJson(const {name} &o) {{").unwrap();
        writeln!(output, "  QJsonArray a;").unwrap();
        for i in 0..elements.len() {
            writeln!(output, "  a.push_back(toJson(std::get<{i}>(o)));").unwrap();
        }
        writeln!(output, "  return a;").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(
            output,
            "inline bool tryFromJson(const QJsonValue &v, {name} &out) {{"
        )
        .unwrap();
        writeln!(output, "  if (!v.isArray()) return false;").unwrap();
        writeln!(output, "  QJsonArray a = v.toArray();").unwrap();
        writeln!(
            output,
            "  if (a.size() != {}) return false;",
            elements.len()
        )
        .unwrap();
        for i in 0..elements.len() {
            writeln!(
                output,
                "  if (!tryFromJson(a.at({i}), std::get<{i}>(out))) return false;"
            )
            .unwrap();
        }
        writeln!(output, "  return true;").unwrap();
        writeln!(output, "}}").unwrap();
    }

    fn generate_tagged_union(&mut self, output: &mut String, uname: &str, variants: &Vec<Variant>) {
        for v in variants {
            for f in &v.fields {
                self.generate(output, &f.ty);
            }
        }
        for Variant { name, fields } in variants {
            self.generate_cpp_struct(output, &format!("{uname}{name}"), fields);
        }
        writeln!(
            output,
            "using {uname} = std::variant<{}>;",
            join_with_comma(
                variants
                    .iter()
                    .map(|Variant { name, .. }| format! {"{uname}{name}"})
            )
        )
        .unwrap();

        writeln!(output, "inline QJsonValue toJson(const {uname} &o) {{").unwrap();
        writeln!(output, "  QJsonObject j;").unwrap();
        writeln!(output, "  std::visit(Hidden::overloaded{{").unwrap();
        for Variant { name: vname, .. } in variants {
            writeln!(
                output,
                r#"    [&j]({uname}{vname} v){{ j = toJson(v).toObject(); j["kind"] = QString("{vname}"); }},"#
            )
            .unwrap();
        }
        writeln!(output, "  }}, o);").unwrap();
        writeln!(output, "  return j;").unwrap();
        writeln!(output, "}}").unwrap();

        writeln!(
            output,
            "inline bool tryFromJson(const QJsonValue &v, {uname} &out) {{",
        )
        .unwrap();
        writeln!(output, "  if (!v.isObject()) return false;").unwrap();
        writeln!(output, "  QJsonObject obj = v.toObject();").unwrap();
        writeln!(
            output,
            "  if (!obj.contains(\"kind\") || !obj[\"kind\"].isString()) return false;"
        )
        .unwrap();
        writeln!(output, "  QString kind = obj.take(\"kind\").toString();").unwrap();
        for Variant { name, .. } in variants {
            writeln!(
                output,
                r#"  if (kind == "{name}") {{ {uname}{name} v; if (!tryFromJson(obj, v)) return false; out = v; return true; }};"#
            )
            .unwrap()
        }
        writeln!(output, "  return false;").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(output).unwrap();
    }

    fn generate_unit_enum(&mut self, output: &mut String, name: &str, variants: &[String]) {
        writeln!(output, "enum class {name} {{").unwrap();
        for (i, v) in variants.iter().enumerate() {
            let comma = if i + 1 < variants.len() { "," } else { "" };
            writeln!(output, "  {}{}", v, comma).unwrap();
        }
        writeln!(output, "}};").unwrap();

        writeln!(output, "inline QJsonValue toJson({name} s) {{",).unwrap();
        writeln!(output, "  switch (s) {{").unwrap();
        for v in variants {
            writeln!(output, "    case {name}::{v}: return \"{v}\";",).unwrap();
        }
        writeln!(output, "  }}").unwrap();
        writeln!(output, "  return QJsonValue::Undefined;").unwrap();
        writeln!(output, "}}").unwrap();

        writeln!(
            output,
            "inline bool tryFromJson(const QJsonValue &v, {name} &out) {{",
        )
        .unwrap();
        writeln!(output, "  if (!v.isString()) return false;").unwrap();
        writeln!(output, "  QString s = v.toString();").unwrap();
        for v in variants {
            writeln!(
                output,
                "  if (s == \"{v}\") {{ out = {name}::{v}; return true; }}",
            )
            .unwrap();
        }
        writeln!(output, "  return false;").unwrap();
        writeln!(output, "}}").unwrap();
    }

    fn generate_cpp_struct(&mut self, output: &mut String, sname: &str, fields: &[Field]) {
        for Field { ty, .. } in fields.iter() {
            self.generate(output, ty);
        }
        writeln!(output, "struct {sname} {{").unwrap();
        for Field { name, ty } in fields {
            let ty_name = ty.qt_type();
            writeln!(output, "  {ty_name} {name};").unwrap();
        }
        writeln!(output, "}};").unwrap();
        writeln!(output, "inline QJsonValue toJson(const {sname} &o) {{",).unwrap();
        writeln!(output, "  QJsonObject j;").unwrap();
        for Field { name, .. } in fields {
            writeln!(output, "  j[\"{name}\"] = toJson(o.{name});",).unwrap();
        }
        writeln!(output, "  return j;").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(
            output,
            "inline bool tryFromJson(const QJsonValue &v, {sname} &out) {{"
        )
        .unwrap();
        writeln!(output, "  if (!v.isObject()) return false;").unwrap();
        writeln!(output, "  QJsonObject obj = v.toObject();").unwrap();
        for Field { name, .. } in fields {
            writeln!(
                output,
                "  if (!tryFromJson(obj[\"{name}\"], out.{name})) return false;",
            )
            .unwrap();
        }
        writeln!(output, "  return true;").unwrap();
        writeln!(output, "}}").unwrap();
    }
    fn generate_optional(&mut self, output: &mut String, inner: &TypeInfo) {
        self.generate(output, inner);
        let ty = inner.qt_type();
        writeln!(output, "inline QJsonValue toJson(const std::optional<{ty}> &o) {{ return o.has_value() ? toJson(o.value()) : QJsonValue::Undefined; }}").unwrap();
        writeln!(
            output,
            "inline bool tryFromJson(const QJsonValue &v, std::optional<{ty}> &out) {{"
        )
        .unwrap();
        writeln!(
            output,
            "    if (v.isUndefined() || v.isNull()) return true;"
        )
        .unwrap();
        writeln!(output, "    {ty} val;").unwrap();
        writeln!(output, "    if (!tryFromJson(v, val)) return false;").unwrap();
        writeln!(output, "    out = val;").unwrap();
        writeln!(output, "    return true;").unwrap();
        writeln!(output, "}}").unwrap();
    }
    fn generate_array(&mut self, output: &mut String, v: &TypeInfo) {
        self.generate(output, v);
        let ty = v.qt_type();
        writeln!(output, "inline QJsonValue toJson(const QList<{ty}> &o) {{").unwrap();
        writeln!(output, "    QJsonArray a;").unwrap();
        writeln!(output, "    for (const auto &i : o) a.append(toJson(i));").unwrap();
        writeln!(output, "    return a;").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(
            output,
            "inline bool tryFromJson(const QJsonValue &v, QList<{ty}> &out) {{"
        )
        .unwrap();
        writeln!(output, "    if (!v.isArray()) return false;").unwrap();
        writeln!(output, "    for (const auto &e : v.toArray()) {{").unwrap();
        writeln!(output, "        {ty} val;").unwrap();
        writeln!(output, "        if (!tryFromJson(e, val)) return false;").unwrap();
        writeln!(output, "        out.append(val);").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output, "    return true;").unwrap();
        writeln!(output, "}}").unwrap();
    }

    fn generate_map(&mut self, output: &mut String, v: &TypeInfo) {
        self.generate(output, v);
        let ty = v.qt_type();
        writeln!(
            output,
            "inline QJsonValue toJson(const QMap<QString, {ty}> &o) {{"
        )
        .unwrap();
        writeln!(output, "    QJsonObject j;").unwrap();
        writeln!(
            output,
            "    for (auto it = o.constKeyValueBegin(); it != o.constKeyValueEnd(); ++it)"
        )
        .unwrap();
        writeln!(output, "        j[it->first] = toJson(it->second);").unwrap();
        writeln!(output, "    return j;").unwrap();
        writeln!(output, "}}").unwrap();
        writeln!(
            output,
            "inline bool tryFromJson(const QJsonValue &v, QMap<QString, {ty}> &out) {{"
        )
        .unwrap();
        writeln!(output, "    if (!v.isObject()) return false;").unwrap();
        writeln!(output, "    auto o = v.toObject();").unwrap();
        writeln!(
            output,
            "    for (auto it = o.constBegin(); it != o.constEnd(); ++it) {{"
        )
        .unwrap();
        writeln!(output, "        {ty} val;").unwrap();
        writeln!(
            output,
            "        if (!tryFromJson(it.value(), val)) return false;"
        )
        .unwrap();
        writeln!(output, "        out[it.key()] = val;").unwrap();
        writeln!(output, "    }}").unwrap();
        writeln!(output, "    return true;").unwrap();
        writeln!(output, "}}").unwrap();
    }
}

fn generate_bool(output: &mut String) {
    output.push_str(
        r#"inline QJsonValue toJson(const bool o) { return {o}; }
inline bool tryFromJson(const QJsonValue &v, bool &out) {
    if (!v.isBool()) return false;
    out = v.toBool();
    return true;
}
"#,
    )
}

fn generate_string(output: &mut String) {
    output.push_str(
        r#"inline QJsonValue toJson(const QString &o) { return {o}; }
inline bool tryFromJson(const QJsonValue &v, QString &out) {
    if (!v.isString()) return false;
    out = v.toString();
    return true;
}
"#,
    )
}

fn generate_number(output: &mut String, ty: &str) {
    writeln!(
        output,
        r#"
inline QJsonValue toJson(const {ty} &o) {{ return static_cast<double>(o); }}
inline bool tryFromJson(const QJsonValue &v, {ty} &out) {{
    if (!v.isDouble()) return false;
    out = static_cast<{ty}>(v.toDouble());
    return true;
}}"#
    )
    .unwrap()
}

fn join_with_comma(els: impl IntoIterator<Item = String>) -> String {
    els.into_iter()
        .reduce(|a, b| a + ", " + &b)
        .unwrap_or_default()
}

#[test]
fn test_string_enum() {
    #[derive(TypeDef)]
    #[allow(unused)]
    enum Foo {
        Bar,
        Baz,
    }
    let mut out = String::new();
    QtJsonGenerator::new().generate(&mut out, &TypeInfo::from(&Foo::INFO));
    insta::assert_snapshot!(out);
}

#[test]
fn test_anonymous_tuple() {
    #[derive(TypeDef)]
    #[allow(unused)]
    struct Foo(Option<(u32, String)>);
    let mut out = String::new();
    QtJsonGenerator::new().generate(&mut out, &TypeInfo::from(&Foo::INFO));
    insta::assert_snapshot!(out);
}

#[test]
fn test_tuple() {
    #[derive(TypeDef)]
    #[allow(unused)]
    struct Foo(u32, String);
    let mut out = String::new();
    QtJsonGenerator::new().generate(&mut out, &TypeInfo::from(&Foo::INFO));
    insta::assert_snapshot!(out);
}

#[test]
fn test_nested_struct() {
    #[derive(TypeDef)]
    #[allow(unused)]
    struct Foo {
        bar: Vec<u8>,
        baz: std::collections::HashMap<String, i8>,
    }
    let mut out = String::new();
    QtJsonGenerator::new().generate(&mut out, &TypeInfo::from(&Foo::INFO));
    insta::assert_snapshot!(out);
}

#[test]
fn test_tagged_enum() {
    #[derive(TypeDef)]
    #[serde(tag = "kind")]
    #[allow(unused)]
    enum Foo {
        Bar { name: String, count: u32 },
        Baz,
    }
    let mut out = String::new();
    QtJsonGenerator::new().generate(&mut out, &TypeInfo::from(&Foo::INFO));
    insta::assert_snapshot!(out);
}

impl Method {
    pub fn to_string_qt(&self /* root_namespace: Option<&str> */) -> String {
        let (args, call) = if !self.is_positional {
            if let Some((name, ty)) = self.args.first() {
                (
                    format!("{} {}", TypeInfo::from(*ty).qt_type(), name),
                    name.to_string(),
                )
            } else {
                ("".to_string(), "QJsonValue::Undefined".to_string())
            }
        } else {
            let args = self
                .args
                .iter()
                .map(|(name, arg)| format!("{} {}", TypeInfo::from(*arg).qt_type(), name))
                .collect::<Vec<String>>()
                .join(", ");
            let call = format!(
                "QJsonArray{{{}}}",
                self.args
                    .iter()
                    .map(|(name, _)| format!("toJson({name})"))
                    .collect::<Vec<_>>()
                    .join(", ")
            );
            (args, call)
        };
        let output = self.output.map_or_else(
            || "void".to_string(),
            |output| TypeInfo::from(output).qt_type(),
        );
        let (output, inner_method) = if !self.is_notification {
            (
                format!("[[nodiscard]] std::future<Result<{output}>>"),
                format!("request<{output}>"),
            )
        } else {
            unimplemented!()
            // (output, "notification")
        };
        let docs = if let Some(docs) = &self.docs {
            let docs = docs.split('\n').fold(String::new(), |mut output, s| {
                let _ = writeln!(output, "   *{s}");
                output
            });
            format!("  /**\n{docs}   */")
        } else {
            "".into()
        };
        let qt_name = &self.ts_name;
        let rpc_name = &self.rpc_name;
        format!(
            r#"{docs}
  {output} {qt_name}({args}) {{
    return {inner_method}("{rpc_name}", {call});
  }}

"#,
        )
    }
}
