[package]
name = "yerpc_derive"
version = "0.5.3"
edition = "2018"
description = "Proc macros for yerpc"
license = "Apache-2.0/MIT"
repository = "https://github.com/deltachat/yerpc"
authors = [
  "Franz Heinzmann <Frando>",
  "Contributors to yerpc"
]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.37"
quote = "1.0.18"
syn = { version = "2.0.68", features = ["full", "parsing", "printing"] }
darling = "0.20.0"
convert_case = "0.5.0"

[features]
openrpc = []
